version: '3'
services:
  searcher:
    build: 
      context: ./shortcut-searcher
      dockerfile: Dockerfile.arm
    container_name: searcher
    depends_on:
      - redis

  processor:
    build:
      context: ./shortcut-processor
      dockerfile: Dockerfile.arm
    container_name: processor
    depends_on:
      - redis
      - db

  transit:
    build:
      context: ./shortcut-transit
      dockerfile: Dockerfile.arm
    container_name: transit
    depends_on:
      - redis
      - db

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    volumes:
      - redisdata:/data
    entrypoint: redis-server --appendonly yes

  db:
    image: postgres:12
    container_name: postgres
    ports:
      - "54320:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shortcut

  migrate:
    build:
      context: ./migrate
      dockerfile: Dockerfile.arm
    container_name: migrate
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/shortcut

  front:
    build:
      context: ./shortcut-front
      dockerfile: Dockerfile.arm
      args:
        - API_URL=http://kansas:3001
    container_name: front
    ports:
      - "8080:80"

  api:
    build:
      context: ./shortcut-api
      dockerfile: Dockerfile.arm
    container_name: api
    ports:
      - "3001:3001"
    depends_on:
      - db
      
volumes:
  dbdata:
  redisdata: