# Dockerfile
FROM arm32v7/node:12
WORKDIR /app
COPY . .
RUN yarn install
RUN ./node_modules/.bin/webpack

FROM alpine:latest
RUN apk add --update nginx && rm -rf /var/cache/apk/*
ADD ./server/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /data/www
COPY index.html /data/www
COPY --from=0 /app/dist /data/www/dist

EXPOSE 80

CMD ["nginx"]